services:
  - type: web
    name: ranking-system
    env: python
    region: ohio
    plan: free
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: reflex run --env prod --loglevel info
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
